services:
  Zeta:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeta
    image: zeta:1.0.0
    ports:
      - "3000:3000"
    environment:
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=http://localhost:3000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-Zeta}?schema=${POSTGRES_SCHEMA:-public}
      - AUTH_SECRET=${AUTH_SECRET:-${NEXTAUTH_SECRET}}
    env_file:
      - .docker.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    restart: always

  db:
    image: postgres:18.4
    container_name: Zeta-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Zeta
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  dozzle:
    image: amir20/dozzle:latest
    container_name: Zeta-logs
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: Zeta-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
