version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: Zeta-postgres
    restart: always
    environment:
      POSTGRES_USER: Zeta
      POSTGRES_PASSWORD: Zeta_password
      POSTGRES_DB: Zeta
    ports:
      - "5432:5432"
    volumes:
      - Zeta_pgdata:/var/lib/postgresql/data

volumes:
  Zeta_pgdata:
